### ISSUE TITLE
ETA react-16 support release

### ISSUE THREAD

**Issue by EXio4** [zeroseven/react-screen-orientation#12]
Is there any ETA for the version that will support react-16?

I see the code has been already merged into develop, so it should be a matter of publishing it to the npm repository

**Comment by amiuhle** [comment]
@EXio4 Could you please install from develop via git, build and verify that it's working on React 16? I currently don't have a project to easily test with.

**Comment by KokzhemyakinaO** [comment]
@amiuhle It is possible to publish an update version React 16?  Thanks

**Comment by EXio4** [comment]
I just checked, and the code seems to work - I was just missing the css

I added a linter setting, and moved the .css among other things

https://github.com/EXio4/react-screen-orientation/commit/6143453a95a87339035a01e68dd5b4b781d852d8

- Can somebody else try this version and confirm if it is working?

**Comment by thecpdubguy** [comment]
> I just checked, and the code seems to work - I was just missing the css
> 
> I added a linter setting, and moved the .css among other things
> 
> [EXio4@6143453](https://github.com/EXio4/react-screen-orientation/commit/6143453a95a87339035a01e68dd5b4b781d852d8)
> 
>     * Can somebody else try this version and confirm if it is working?

I can confirm that this one works for me as well.

**Comment by thecpdubguy** [comment]
Any updates on this? Or do you want a new maintainer?

**Comment by amiuhle** [comment]
Published `v0.0.4`, sorry it took so long.
