### ISSUE TITLE
TypeError on Safari

### ISSUE THREAD

**Issue by gillescochez** [zeroseven/react-screen-orientation#3]
On safari getting the following error.

> TypeError: undefined is not an object (evaluating 'window.screen.orientation.type')

On a Mac laptop and without any orientation changes occurring, happening on page rendering.

**Comment by brunnobb** [comment]
I saw this error, can you please try my fork, may work for you..
I did also some changes for android pre 4.4, because it was not compatible.

**Comment by mikecharles** [comment]
Anything new with this error?

**Comment by brunnobb** [comment]
dont load the package from npm, instead use it like 
"react-screen-orientation": "git+https://github.com/zeroseven/react-screen-orientation.git",
on your package.json as npm package is outdated and im in a hurry in the moment

**Comment by charj** [comment]
Just to confirm, @brunnobb's comment does fix the issue at hand.

Are you working towards a new version in which you integrate this fix?
We would prefer to use a version number in our `package.json`.

Thanks.

**Comment by charj** [comment]
Morning @amiuhle,
Can you publish the latest version of this package to npm to resolve this issue?

**Comment by amiuhle** [comment]
I just published `0.0.3`, can you please confirm this fixes the issue?

**Comment by charj** [comment]
Awesome. Thanks @amiuhle.
`0.0.3 in our `package.json` fixes this problem.

Thanks a bunch.

**Comment by amiuhle** [comment]
No problem, sorry it took a while.
