### ISSUE TITLE
Does not work with a React 15.5 peer dependency

### ISSUE THREAD

**Issue by CharlieHess** [zeroseven/react-screen-orientation#7]
If you have a peer of React >= `15.5`, you'll see this error:

```
Uncaught TypeError: Cannot read property 'bool' of undefined
    at Object../node_modules/react-screen-orientation/lib/index.js (index.js:53)
```

This is because since `15.5`, `PropTypes` is defined in a separate package. This can be fixed by merging https://github.com/zeroseven/react-screen-orientation/pull/6.

**Comment by jcampbellg** [comment]
How I can fix this issue? I'm using React ^16.4.1
